default: &default 
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: desarrollo_db

test:
  <<: *default
  database: prueba_db

production:
  <<: *default
  database: produccion_db
